name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Menjalankan workflow ketika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan di runner GitHub Actions berbasis Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SECRET_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EC2 Instance
        id: ec2_create
        run: |
          # Membuat instance EC2 menggunakan AWS CLI
          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0df8c184d5f6ae949 --count 1 --instance-type t2.micro --key-name vockey --security-group-ids sg-0ed43e7ec526488de --subnet-id subnet-09de9002777e220c2 --query "Instances[0].InstanceId" --output text)
          echo "Instance ID: $INSTANCE_ID"
          echo "::set-output name=instance_id::$INSTANCE_ID"
        
      - name: Wait for EC2 Instance to be Running
        run: |
          aws ec2 wait instance-running --instance-ids ${{ steps.ec2_create.outputs.instance_id }}

      - name: Get Public IP of EC2 Instance
        id: ec2_ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ steps.ec2_create.outputs.instance_id }} --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "Public IP: $PUBLIC_IP"
          echo "::set-output name=public_ip::$PUBLIC_IP"
        
      - name: Install Node.js and Dependencies
        run: |
          # SSH ke EC2 instance dan install Node.js
          ssh -o StrictHostKeyChecking=no -i my-key.pem ec2-user@${{ steps.ec2_ip.outputs.public_ip }} << 'EOF'
            sudo yum update -y
            curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
            sudo yum install -y nodejs
            git clone https://github.com/dihkaw/showipserverwithnodejs.git
            cd showipserverwithnodejs
            npm install
            npm start &
          EOF
