name : build and upload to s3

on:
  push:
    branches:
      - main
      
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # ganti dengan versi Node.js yang kamu pakai

      - name: Install dependencies
        run: |
          npm install

  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: cekot repo
        uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: make zip
        run: |
          zip -r nodejsapp.zip .ebextensions/ index.js package.json package.lock.json playbook.yml

      - name:
        run: |
          aws s3 cp nodejsapp.zip s3://${{ secrets.S3_BUCKET_NAME }}/nodejsapp.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}